---
title: "Suzanne Combs"
subtitle: "BIOL 3100 - Final Project"
output: 
  html_document:
    code_folding: hide
date: "2024-12-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Load packages
library(tidyverse)
library(modelr)
library(janitor)
library(patchwork)


```

# Background

```{r, include=FALSE}
# Load the data
df <- read_csv("./Sleep_health_and_lifestyle_dataset.csv")

## Clean the data
df_clean <- clean_names(df)

# Separate the blood pressure into systolic and diastolic
df_clean <- df_clean %>% 
  separate(blood_pressure, into = c("systolic", "diastolic"), sep = "/")

# Change the data types to be factors or numeric
df_clean$gender <- as.factor(df_clean$gender)
df_clean$occupation <- as.factor(df_clean$occupation)
df_clean$bmi_category <- as.factor(df_clean$bmi_category)
df_clean$sleep_disorder <- as.factor(df_clean$sleep_disorder)
df_clean$systolic <- as.numeric(df_clean$systolic)
df_clean$diastolic <- as.numeric(df_clean$diastolic)

```

# Visualization 

```{r}
df_clean %>% 
  ggplot(aes(x=stress_level, y = quality_of_sleep, color=occupation)) +
  geom_jitter() +
  geom_smooth(method="lm", se=FALSE) +
  facet_wrap(~occupation, scales="free")

df_clean %>% 
  ggplot(aes(x=gender, y = quality_of_sleep, fill=gender)) +
  geom_violin() 

df_clean %>% 
  ggplot(aes(x=age, y = quality_of_sleep, color=(gender))) +
  geom_jitter(alpha=0.75) +
  geom_smooth(se=FALSE, method="lm")

df_clean %>% 
  ggplot(aes(x=age, y = quality_of_sleep)) +
  geom_point() +
  geom_smooth(se=FALSE)

p1 <- df_clean %>% 
  ggplot(aes(x=occupation, y = quality_of_sleep, fill=occupation)) +
  geom_violin()

# Same as before but sleep duration. Put these two side by side
p2 <- df_clean %>% 
  ggplot(aes(x=occupation, y = sleep_duration, fill=occupation)) +
  geom_violin()

p1 + p2

df_clean %>% 
  ggplot(aes(x=sleep_disorder, y = quality_of_sleep, fill=sleep_disorder)) +
  geom_violin() +
  facet_wrap(~occupation)

df_clean %>% 
  ggplot(aes(x=sleep_disorder, y = quality_of_sleep, fill=sleep_disorder)) +
  geom_violin()

```

# Modeling
```{r}
mod3 <- glm(data=df_clean, formula = quality_of_sleep ~ age + occupation + stress_level)
summary(mod3)
plot(mod3$residuals)
mean(mod3$residuals^2)
```